# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: /
    weight: 30
  - name: Research
    url: project/
    weight: 40
  - name: Towards Data Science
    url: /#towards_data_science
    weight: 50
  # - name: Papers
  #   url: /#papers
  #   weight: 15
  # - name: Talks
  #   url: /#talks
  #   weight: 12
  # - name: News
  #   url: /#news
  #   weight: 13
  # - name: Experience
  #   url: experience/ # experience md file  name indicating a new page
  #   weight: 16
  # - name: Projects
  #   url: project/ # project is the folder  indicating a new page
  #   weight: 17
  # - name: Teaching
  #   url: teaching/ # teaching is the folder  indicating a new page
  #   weight: 18
  
