# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Me
    url: /
    weight: 10
  - name: Research
    url: /#research
    weight: 11
  - name: Research
    url: /#research
    weight: 13
  - name: Towards Data Science
    url: /#towards_data_science
    weight: 14
  - name: Papers
    url: /#papers
    weight: 15
  # - name: Talks
  #   url: /#talks
  #   weight: 12
  # - name: News
  #   url: /#news
  #   weight: 13
  - name: Experience
    url: experience/ # experience is the folder or md file  name indicating a new page
    weight: 16
  - name: Projects
    url: project/
    weight: 17
  - name: Teaching
    url: teaching/
    weight: 18
  
